### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by mangapi** [crossvertise/ActionMailerNext#11]
Hi there!

I am using ActionMailerNext (in mvc 5 project)  for the first time and i was wondering if there is any tutorial/example on how to unit test this.

Any one know how to go about it? 

Cheers

**Comment by hydr** [comment]
I created a wiki entry for it 
https://github.com/crossvertise/ActionMailerNext/wiki/8.-Unit-Testing
hope this makes it easier :)
